spring:
  application:
    name: ToDoList

  profiles:
    active:
      - prod

  datasource:
    url: jdbc:mysql://localhost:3306/todolistlib?serverTimezone=Europe/Moscow
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: 'validate'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  liquibase:
    enabled: false
    change-log: classpath:db.changelog/db.changelog.master.xml

server:
  port: 8888
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 1h

logging:
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        security: INFO