spring:
  application:
    name: ToDoList

  datasource:
    url: jdbc:mysql://localhost:3306/todolistlib?serverTimezone=Europe/Moscow
    username: root
    password: root
server:
  port: 8888
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 1h

logging:
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        security: INFO